package:
  name: fasttext
  version: "0.8.22"

source:
  path: ../fastText 
requirements:
  host:
    - python
    - setuptools
    - pybind11

  run:
    - python
    - numpy
    - scipy
    - pybind11

test:
  source_files:
    - runtests.py
  imports:
    - fastText
  commands:
    - python runtests.py -u

about:
  home: https://fasttext.cc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  license: BSD-3-Clause
