task:
  container:
    image: continuumio/anaconda3:latest
  script: 
    - python --version
    - conda --version
    - conda install conda-build libarchive python-libarchive-c
    - ls
    - conda build receipe


